### ISSUE TITLE
Wrong url return with enablePrettyUrl = true

### ISSUE THREAD

**Issue by minhnguyenerp** [dmirogin/yii2-js-urlmanager#2]
UrlManager.createUrl('/foo/bar', {id:10}); will return "/foo/barnull?id=10"

Its automatically add "null" to the url path.

Here is the Yii2 urlManager configuration:
'urlManager' => [
            'enablePrettyUrl' => true,
            'showScriptName' => false,
            'rules' => [
            ],
        ],

**Comment by dmirogin** [comment]
Thanks for feedback. I can handle it in 2 days.

**Comment by mcserep** [comment]
This issue still exists in version 1.2.0.

**Comment by buttflattery** [comment]
Yes this issue still persists @mcserep

**Comment by dmirogin** [comment]
Sorry, don't have time to resolve it.
