### ISSUE TITLE
Url path in local development

### ISSUE THREAD

**Issue by minhnguyenerp** [dmirogin/yii2-js-urlmanager#3]
I'm using the Yii2 basic template. In local development, my application URL is http://localhost/basic/web

This line in Yii **\yii\helpers\Url::to(['/foo/bar', 'id'=>10]);** will generate "_/basic/web/foo/bar?id=10_" in local server, and generate "_/foo/bar?id=10_" in production server.

In Js-Urlmanager, both local and production server, it only generate "_/foo/bar?id=10_". With this, its working as expected in production server, but its not working in the local server. It will be painful for developers because most of the time they need to work with local server.

**Comment by dmirogin** [comment]
I got it. Why don't you configure your local document root inside basic/Web directory?

**Comment by minhnguyenerp** [comment]
I have several applications in the local server, for example http://localhost/erp/web, http://localhost/cms/web,...

If I set the document root to the /web directory, I have to switch between them through the vhost config frequently

**Comment by dmirogin** [comment]
You can define different servers whatever you use (nginx, apache2)

**Comment by minhnguyenerp** [comment]
Yes I know how to define those virtual host. Thats the only way I can do to make the Js-Urlmanager working in local server right now

**Comment by minhnguyenerp** [comment]
You can mark this as an enhanced feature

**Comment by dmirogin** [comment]
Yeah, I think so too. Need consider baseUrl. Thanks for feedback.

**Comment by minhnguyenerp** [comment]
Thank you
